### ISSUE TITLE
MToolBox-f527c5c, assembleMTgenome.py

### ISSUE THREAD

**Issue by 3i-v** [mitoNGS/MToolBox#72]
I am running the last MToolBox commit (MToolBox-f527c5c), but here is the error message I obtained on a sample that previously failed (with the older version);
Thank you,
v.
------------
[Fri Feb 08 18:13:10 EST 2019] net.sf.picard.sam.SamFormatConverter done. Elapsed time: 0.09 minutes.
Runtime.totalMemory()=602406912

##### ASSEMBLING MT GENOMES WITH ASSEMBLEMTGENOME...

WARNING: values of tail < 5 are deprecated and will be replaced with 5

[mpileup] 1 samples in 1 input files
Traceback (most recent call last):
  File "xxx/MToolBox-f527c5c_20190206/MToolBox/assembleMTgenome.py", line 445, in <module>
    mut_events = mtvcf_main_analysis(mt_table, sam_file, sample_name, tail=tail)
  File "xxx/MToolBox-f527c5c_20190206/MToolBox/mtVariantCaller.py", line 590, in mtvcf_main_analysis
    Covbase.append(median(convert))
  File "xxx/MToolBox-f527c5c_20190206/MToolBox/mtVariantCaller.py", line 65, in median
    m1 = sorted(l)[(len(l)/2)+1-1]
IndexError: list index out of range

**Comment by clody23** [comment]
Hi,
can you please share the input file that generates this error? That will help debugging.

thanks
Best wishes,
Claudia

**Comment by 3i-v** [comment]
Hi Claudia,
Could you please sent me an eMail I can use to share the files with you ? You can sent it to me at
vr.saillour@gmail.com
Thank you so much,
v.

**Comment by clody23** [comment]
Hi,

thanks for sending the files. This https://github.com/mitoNGS/MToolBox/commit/58f3db1b2d86715ae4fd56f014edd5b9dd212be1 should fix the issue now. 

Best,
Claudia

**Comment by 3i-v** [comment]
Thank you very much for the update Claudia. With the commit 58f3db1 you made, I was able to recover 5 on 8 analysis that previously failed. A bug is still persistent on 3 samples. The error messsage I obtain is this one:

```
##### ASSEMBLING MT GENOMES WITH ASSEMBLEMTGENOME...

WARNING: values of tail < 5 are deprecated and will be replaced with 5

[mpileup] 1 samples in 1 input files
Traceback (most recent call last):
  File "(...)/MToolBox/assembleMTgenome.py", line 445, in <module>
    mut_events = mtvcf_main_analysis(mt_table, sam_file, sample_name, tail=tail)
  File "(...)/MToolBox/mtVariantCaller.py", line 563, in mtvcf_main_analysis
    Refbase=mtDNAseq[int(i)-1]
IndexError: string index out of range

##### GENERATING VCF OUTPUT...
Traceback (most recent call last):
  File "(...)/MToolBox/VCFoutput.py", line 36, in <module>
    VCF_dict = ast.literal_eval(open('VCF_dict_tmp', 'r').read())
IOError: [Errno 2] No such file or directory: 'VCF_dict_tmp'
```

Thank you,
v.
